spring:
  application:
    name: order-service

server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

##feign中的hystrix(熔断、降级)没有开启
feign:
  hystrix:
    enabled: true

##配置健康检查actuator
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#---
#spring:
#  profiles: order1
#
#server:
#  port: 8201
#---
#spring:
#  profiles: order2
#server:
#  port: 8202