#---
#spring:
#  profiles: user1
#
#server:
#  port: 8101
#---
#spring:
#  profiles: user2
#server:
#  port: 8102
#---
sp:
  user-service:
    users: "[{\"id\":722, \"username\":\"abcfgb\",\"password\":\"12321\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.253.133
    port: 5672
    username: root
    password: 123456

server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
